import React from 'react'
import Head from 'next/head'
import style from '../styles/layaout.module.css'
import Menu from './Menu'

export default function Layaout({children, title}) {
 
  return (
    <div>
        <Head>
            <title>{title ? `${title}` : ""}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Menu/>
        
        <div className={style.container}>
            {children}
        </div>
    </div>

  )
}
